# backend/send_report_now.py
import io
import os
from dotenv import load_dotenv

# load .env
load_dotenv()

from flask import Flask
from flask_mail import Mail, Message
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import matplotlib.pyplot as plt

# App config from env
MAIL_SERVER = os.getenv("MAIL_SERVER", "smtp.gmail.com")
MAIL_PORT = int(os.getenv("MAIL_PORT", 587))
MAIL_USE_TLS = os.getenv("MAIL_USE_TLS", "1") in ("1", "True", "true")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER", MAIL_USERNAME)
TEST_RECIPIENT = os.getenv("TEST_RECIPIENT", MAIL_USERNAME)

app = Flask(__name__)
app.config.update(
    MAIL_SERVER=MAIL_SERVER,
    MAIL_PORT=MAIL_PORT,
    MAIL_USE_TLS=MAIL_USE_TLS,
    MAIL_USERNAME=MAIL_USERNAME,
    MAIL_PASSWORD=MAIL_PASSWORD,
    MAIL_DEFAULT_SENDER=MAIL_DEFAULT_SENDER,
)

mail = Mail(app)

def build_pdf():
    """Return BytesIO containing PDF with a small chart and text."""
    # Create small matplotlib plot in memory
    fig, ax = plt.subplots(figsize=(4, 2.4))
    regions = ["NA", "EU", "APAC"]
    sales = [5000000, 3200000, 2100000]
    ax.bar(regions, sales)
    ax.set_title("Sales by Region")
    ax.set_ylabel("Total Sales")
    plt.tight_layout()

    chart_buf = io.BytesIO()
    plt.savefig(chart_buf, format="png", bbox_inches="tight")
    plt.close(fig)
    chart_buf.seek(0)
    chart_img = ImageReader(chart_buf)

    # Create PDF in memory and embed chart
    pdf_buf = io.BytesIO()
    c = canvas.Canvas(pdf_buf, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, "Weekly Manager KPI Report (Test)")
    c.setFont("Helvetica", 12)
    c.drawString(100, 730, "This PDF was generated by send_report_now.py (test).")
    # draw chart image (x, y, width, height)
    c.drawImage(chart_img, 100, 420, width=360, height=200)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(100, 400, "Generated programmatically for verification.")
    c.showPage()
    c.save()
    pdf_buf.seek(0)
    return pdf_buf

def send_test_email(recipient):
    with app.app_context():
        pdf_buf = build_pdf()
        msg = Message(subject="Test Weekly KPI Report", recipients=[recipient])
        msg.body = "Hi — attached is a test weekly KPI report (PDF)."
        msg.attach("weekly_report.pdf", "application/pdf", pdf_buf.read())
        # send and catch errors
        try:
            mail.send(msg)
            print(f"✅ Email successfully sent to {recipient}")
            return True
        except Exception as e:
            print("❌ Failed to send email. See exception below:")
            # print full exception for debugging
            import traceback
            traceback.print_exc()
            return False

if __name__ == "__main__":
    print("Mail server:", MAIL_SERVER, "port:", MAIL_PORT, "use_tls:", MAIL_USE_TLS)
    if not MAIL_USERNAME or not MAIL_PASSWORD:
        print("ERROR: MAIL_USERNAME or MAIL_PASSWORD not set in .env. Edit backend/.env and add them.")
    else:
        success = send_test_email(TEST_RECIPIENT)
        if not success:
            print("Check the exception above and follow the troubleshooting steps in the README.")
