# backend/tasks.py

from celery_worker import celery
from flask_mail import Message
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import matplotlib.pyplot as plt
from app import create_app, db, mail
from app.models import User
from db.clickhouse_client import fetch_region_kpis   # ✅ New import

# Create Flask app for Celery
flask_app = create_app()


def generate_combined_pdf(manager):
    """Generate a PDF with global + region-specific KPI data"""

    # === GLOBAL DATA ===
    global_data = fetch_region_kpis(region="ALL", date_range="last_7_days")
    if not global_data:
        global_data = [
            {"region": "NA", "total_sales": 0},
            {"region": "EU", "total_sales": 0},
            {"region": "APAC", "total_sales": 0},
        ]

    # === GLOBAL CHART ===
    fig1, ax1 = plt.subplots(figsize=(4, 3))
    regions = [k["region"] for k in global_data]
    sales = [k["total_sales"] for k in global_data]
    ax1.bar(regions, sales, color="lightgreen")
    ax1.set_title("Global Sales by Region")
    plt.tight_layout()

    global_chart_buf = io.BytesIO()
    plt.savefig(global_chart_buf, format="png")
    plt.close(fig1)
    global_chart_buf.seek(0)
    global_chart_img = ImageReader(global_chart_buf)

    # === REGION-SPECIFIC DATA ===
    manager_region = getattr(manager, "region", "NA")
    region_data = fetch_region_kpis(manager_region, date_range="last_7_days")

    if not region_data:
        region_data = [{"region": manager_region, "total_sales": 0}]

    fig2, ax2 = plt.subplots(figsize=(4, 3))
    ax2.bar([k["region"] for k in region_data], [k["total_sales"] for k in region_data], color="skyblue")
    ax2.set_title(f"Sales Report - {manager_region}")
    ax2.set_ylabel("Total Sales")
    plt.tight_layout()

    region_chart_buf = io.BytesIO()
    plt.savefig(region_chart_buf, format="png")
    plt.close(fig2)
    region_chart_buf.seek(0)
    region_chart_img = ImageReader(region_chart_buf)

    # === BUILD PDF ===
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)

    # Title
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(150, 750, f"Weekly KPI Report - {manager.username}")

    # Greeting
    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 720, f"Hello {manager.username},")
    pdf.drawString(100, 700, "Here is your weekly KPI performance update:")

    # Insert GLOBAL chart
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(100, 670, "🌍 Global Sales Overview")
    pdf.drawImage(global_chart_img, 100, 440, width=360, height=200)

    # Insert REGION-specific details
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(100, 410, f"📊 {manager_region} Region Performance")
    y = 390
    for k in region_data:
        pdf.setFont("Helvetica", 12)
        pdf.drawString(100, y, f"{k['region']} Sales: ${k['total_sales']:,}")
        y -= 20

    pdf.drawImage(region_chart_img, 100, 160, width=300, height=180)

    # Footer
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(100, 140, "Generated by Data Analytics Dashboard")

    # Finalize
    pdf.showPage()
    pdf.save()
    buffer.seek(0)

    return buffer


def generate_region_pdf(manager):
    """Generate a PDF with only region-specific KPI data"""
    # ✅ Get live data from ClickHouse
    data = fetch_region_kpis(manager.region, date_range="last_7_days")

    if not data:
        data = [{"region": manager.region, "total_sales": 0, "new_customers": 0, "churn_rate": 0}]

    # Build chart
    fig, ax = plt.subplots(figsize=(4, 3))
    regions = [k["region"] for k in data]
    sales = [k["total_sales"] for k in data]
    ax.bar(regions, sales, color="skyblue")
    ax.set_title(f"Sales Report - {manager.region}")
    ax.set_ylabel("Total Sales")
    plt.tight_layout()

    chart_buffer = io.BytesIO()
    plt.savefig(chart_buffer, format="png")
    plt.close(fig)
    chart_buffer.seek(0)
    chart_img = ImageReader(chart_buffer)

    # Build PDF
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(150, 750, f"Weekly KPI Report - {manager.region}")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 720, f"Hello {manager.username},")
    pdf.drawString(100, 700, "Here are your weekly KPIs:")

    y = 660
    for k in data:
        pdf.drawString(100, y, f"Sales: ${k['total_sales']:,}")
        y -= 20
        pdf.drawString(100, y, f"New Customers: {k.get('new_customers', 0)}")
        y -= 20
        pdf.drawString(100, y, f"Churn Rate: {k.get('churn_rate', 0):.2f}%")
        y -= 40

    pdf.drawImage(chart_img, 100, 400, width=300, height=200)

    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(100, 380, "Generated by Data Analytics Dashboard")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)

    return buffer


@celery.task
def send_weekly_reports():
    """Celery task to email all managers with global + region-specific KPI reports"""
    with flask_app.app_context():
        managers = User.query.filter_by(role="manager").all()

        for manager in managers:
            # Use combined PDF (global + region) OR switch to region-only if preferred
            pdf_buffer = generate_combined_pdf(manager)
            # pdf_buffer = generate_region_pdf(manager)  # <- alternative

            manager_region = getattr(manager, "region", "NA")

            msg = Message(
                subject="Weekly KPI Report",
                recipients=[manager.email],
                body=(
                    f"Hello {manager.username},\n\n"
                    f"Attached is your weekly KPI report with global and {manager_region} insights."
                )
            )
            msg.attach("weekly_report.pdf", "application/pdf", pdf_buffer.read())
            mail.send(msg)

        return f"✅ Sent combined reports to {[m.email for m in managers]}"
