
from flask import Blueprint, request, jsonify, Response, send_file
import csv
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import matplotlib.pyplot as plt

api_bp = Blueprint("api", __name__)

# -------------------------
# Mock KPI dataset
# -------------------------
MOCK_KPIS = [
    {"region": "NA", "total_sales": 5000000},
    {"region": "EU", "total_sales": 3200000},
    {"region": "APAC", "total_sales": 2100000},
]

# -------------------------
# KPI Summary Endpoint
# -------------------------
@api_bp.route("/kpi-summary", methods=["GET"])
def get_kpi_summary():
    # Get filters from query parameters
    date_range = request.args.get("dateRange", "last_30_days")
    region = request.args.get("region", "all")

    # Apply region filter
    data = MOCK_KPIS
    if region != "all":
        data = [kpi for kpi in MOCK_KPIS if kpi["region"] == region]

    # Apply date range adjustments (mock logic)
    if date_range == "last_7_days":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 0.2)} for kpi in data]
    elif date_range == "last_90_days":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 1.5)} for kpi in data]
    elif date_range == "year_to_date":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 4)} for kpi in data]

    return jsonify(data)

# -------------------------
# CSV Export Endpoint
# -------------------------
@api_bp.route("/export-csv", methods=["GET"])
def export_csv():
    # Get filters from query parameters
    date_range = request.args.get("dateRange", "last_30_days")
    region = request.args.get("region", "all")

    # Apply region filter
    data = MOCK_KPIS
    if region != "all":
        data = [kpi for kpi in MOCK_KPIS if kpi["region"] == region]

    # Apply date range adjustments (mock logic)
    if date_range == "last_7_days":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 0.2)} for kpi in data]
    elif date_range == "last_90_days":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 1.5)} for kpi in data]
    elif date_range == "year_to_date":
        data = [{**kpi, "total_sales": int(kpi["total_sales"] * 4)} for kpi in data]

    # Generate CSV in memory
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=["region", "total_sales"])
    writer.writeheader()
    writer.writerows(data)

    # Return CSV file
    response = Response(output.getvalue(), mimetype="text/csv")
    response.headers["Content-Disposition"] = "attachment; filename=kpi_export.csv"
    return response

# -------------------------
# PDF Export Endpoint (Updated with Chart + Data)
# -------------------------
@api_bp.route("/generate-pdf", methods=["GET"])
def generate_pdf():
    date_range = request.args.get("dateRange", "last_30_days")
    region = request.args.get("region", "all")

    # Start with mock data
    kpi_data = MOCK_KPIS

    # Filter dataset
    if region != "all":
        kpi_data = [k for k in kpi_data if k["region"] == region]

    # ✅ Generate chart with Matplotlib
    fig, ax = plt.subplots(figsize=(4, 3))
    regions = [k["region"] for k in kpi_data]
    sales = [k["total_sales"] for k in kpi_data]
    ax.bar(regions, sales, color="skyblue")
    ax.set_title("Sales by Region")
    ax.set_ylabel("Total Sales")
    plt.tight_layout()

    # Save chart to memory
    chart_buffer = io.BytesIO()
    plt.savefig(chart_buffer, format="png")
    plt.close(fig)  # Free memory
    chart_buffer.seek(0)
    chart_img = ImageReader(chart_buffer)

    # ✅ Build PDF
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)

    # Report Title
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(200, 750, "Manager KPI Report")

    # Subheading
    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 720, f"Date Range: {date_range}")
    pdf.drawString(100, 700, f"Region: {region}")

    # KPI summary
    y = 660
    for k in kpi_data:
        pdf.drawString(100, y, f"{k['region']} - Sales: ${k['total_sales']:,}")
        y -= 20

    # Embed chart image
    pdf.drawImage(chart_img, 100, 400, width=300, height=200)

    # Footer
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(100, 380, "Generated by Data Analytics Dashboard")

    pdf.showPage()
    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="manager_report.pdf",
        mimetype="application/pdf"
    )


















# from flask import Blueprint, request, jsonify, Response, send_file
# import csv
# import io
# from reportlab.lib.pagesizes import letter
# from reportlab.pdfgen import canvas

# api_bp = Blueprint("api", __name__)

# # -------------------------
# # Mock KPI dataset
# # -------------------------
# MOCK_KPIS = [
#     {"region": "NA", "total_sales": 5000000},
#     {"region": "EU", "total_sales": 3200000},
#     {"region": "APAC", "total_sales": 2100000},
# ]

# # -------------------------
# # KPI Summary Endpoint
# # -------------------------
# @api_bp.route("/kpi-summary", methods=["GET"])
# def get_kpi_summary():
#     # Get filters from query parameters
#     date_range = request.args.get("dateRange", "last_30_days")
#     region = request.args.get("region", "all")

#     # Apply region filter
#     data = MOCK_KPIS
#     if region != "all":
#         data = [kpi for kpi in MOCK_KPIS if kpi["region"] == region]

#     # Apply date range adjustments (mock logic)
#     if date_range == "last_7_days":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 0.2)} for kpi in data]
#     elif date_range == "last_90_days":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 1.5)} for kpi in data]
#     elif date_range == "year_to_date":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 4)} for kpi in data]

#     return jsonify(data)

# # -------------------------
# # CSV Export Endpoint
# # -------------------------
# @api_bp.route("/export-csv", methods=["GET"])
# def export_csv():
#     # Get filters from query parameters
#     date_range = request.args.get("dateRange", "last_30_days")
#     region = request.args.get("region", "all")

#     # Apply region filter
#     data = MOCK_KPIS
#     if region != "all":
#         data = [kpi for kpi in MOCK_KPIS if kpi["region"] == region]

#     # Apply date range adjustments (mock logic)
#     if date_range == "last_7_days":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 0.2)} for kpi in data]
#     elif date_range == "last_90_days":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 1.5)} for kpi in data]
#     elif date_range == "year_to_date":
#         data = [{**kpi, "total_sales": int(kpi["total_sales"] * 4)} for kpi in data]

#     # Generate CSV in memory
#     output = io.StringIO()
#     writer = csv.DictWriter(output, fieldnames=["region", "total_sales"])
#     writer.writeheader()
#     writer.writerows(data)

#     # Return CSV file
#     response = Response(output.getvalue(), mimetype="text/csv")
#     response.headers["Content-Disposition"] = "attachment; filename=kpi_export.csv"
#     return response

# # -------------------------
# # PDF Export Endpoint
# # -------------------------
# @api_bp.route("/generate-pdf", methods=["GET"])
# def generate_pdf():
#     # Get filters (optional for future use)
#     date_range = request.args.get("dateRange", "last_30_days")
#     region = request.args.get("region", "all")

#     # Create in-memory PDF
#     buffer = io.BytesIO()
#     pdf = canvas.Canvas(buffer, pagesize=letter)

#     # Report Title
#     pdf.setFont("Helvetica-Bold", 16)
#     pdf.drawString(200, 750, "Manager KPI Report")

#     # Subheading
#     pdf.setFont("Helvetica", 12)
#     pdf.drawString(100, 720, f"Date Range: {date_range}")
#     pdf.drawString(100, 700, f"Region: {region}")

#     # Example KPI data (mock for now)
#     pdf.drawString(100, 660, "Total Sales: $5,000,000")
#     pdf.drawString(100, 640, "New Customers: 1,245")
#     pdf.drawString(100, 620, "Churn Rate: 4.2%")

#     # Footer
#     pdf.setFont("Helvetica-Oblique", 10)
#     pdf.drawString(100, 580, "Generated by Data Analytics Dashboard")

#     pdf.showPage()
#     pdf.save()
#     buffer.seek(0)

#     return send_file(
#         buffer,
#         as_attachment=True,
#         download_name="manager_report.pdf",
#         mimetype="application/pdf"
#     )
